//
// Created by Iago Ferreira on 10/02/2021.
//

#ifndef PHARMACY_MANAGEMENT_CONTROLLER_NOTAFISCAL_H
#define PHARMACY_MANAGEMENT_CONTROLLER_NOTAFISCAL_H

#endif //PHARMACY_MANAGEMENT_CONTROLLER_NOTAFISCAL_H
